import { CompletedBooking, PendingBooking, UpcomingBooking } from '@/components/common/svg/BookingSVG'
import { AvailableCars } from '@/components/common/svg/dashboardSVG'
import { Calendar, Clock, CheckCircle, Car } from 'lucide-react'

// Booking statistics data
export const bookingStats = [
    {
        title: 'Upcoming Bookings',
        value: 145,
        description: 'From Last Week',
        icon: UpcomingBooking,
        bgColor: '#FFF',
        iconBgColor: 'bg-blue-100',
        iconColor: 'text-blue-600',
    },
    {
        title: 'Pending Bookings',
        value: 367,
        description: 'From Last Week',
        icon: PendingBooking,
        bgColor: '#FFF',
        iconBgColor: 'bg-yellow-100',
        iconColor: 'text-yellow-600',
    },
    {
        title: 'Completed Bookings',
        value: 145,
        description: 'From Last Week',
        icon: CompletedBooking,
        bgColor: '#FFF',
        iconBgColor: 'bg-green-100',
        iconColor: 'text-green-600',
    },
    {
        title: 'Available Cars',
        value: 245,
        description: 'From Last Week',
        icon: AvailableCars,
        bgColor: '#FFF',
        iconBgColor: 'bg-teal-100',
        iconColor: 'text-teal-600',
    },
]

// Car bookings data for the table
export const carBookingsData = [
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2026',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '€500',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2025',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '€350',
        paymentStatus: 'Pending',
        status: 'Runing',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2026',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '$500',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2025',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '€350',
        paymentStatus: 'Pending',
        status: 'Upcoming',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2025',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '$500',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2025',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '€350',
        paymentStatus: 'Pending',
        status: 'Runing',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2026',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '€350',
        paymentStatus: 'Pending',
        status: 'Upcoming',
    },
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2026',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        carModel: 'Toyota Corolla',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '$500',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
]

// Filter options for status
export const statusFilterOptions = [
    { value: 'all', label: 'All Status' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Runing', label: 'Runing' },
    { value: 'Upcoming', label: 'Upcoming' },
]
