import { CompletedBooking, PendingBooking, UpcomingBooking } from '@/components/common/svg/BookingSVG'
import { AvailableCars } from '@/components/common/svg/dashboardSVG'
import { Calendar, Clock, CheckCircle, Car } from 'lucide-react'

// Booking statistics data
export const bookingStats = [
    {
        title: 'Upcoming Bookings',
        value: 145,
        description: 'From Last Week',
        icon: UpcomingBooking,
        bgColor: '#FFF',
        iconBgColor: 'bg-blue-100',
        iconColor: 'text-blue-600',
    },
    {
        title: 'Pending Bookings',
        value: 367,
        description: 'From Last Week',
        icon: PendingBooking,
        bgColor: '#FFF',
        iconBgColor: 'bg-yellow-100',
        iconColor: 'text-yellow-600',
    },
    {
        title: 'Completed Bookings',
        value: 145,
        description: 'From Last Week',
        icon: CompletedBooking,
        bgColor: '#FFF',
        iconBgColor: 'bg-green-100',
        iconColor: 'text-green-600',
    },
    {
        title: 'Available Cars',
        value: 245,
        description: 'From Last Week',
        icon: AvailableCars,
        bgColor: '#FFF',
        iconBgColor: 'bg-teal-50',
        iconColor: 'text-teal-600',
    },
]

// Car bookings data for the table
export const carBookingsData = [
    {
        id: 'Ik-20248',
        startDate: '21 Aug 2026',
        endDate: '26 Aug 2026',
        clientName: 'Alice Jhonson',
        clientEmail: 'alice@example.com',
        clientPhone: '+1 234 567 890',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Toyota Corolla',
        carModel: 'Toyota Corolla 2026',
        licensePlate: 'TX1234',
        plan: '2 Days',
        payment: '€500',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20249',
        startDate: '15 Sep 2026',
        endDate: '18 Sep 2026',
        clientName: 'Michael Smith',
        clientEmail: 'michael@example.com',
        clientPhone: '+1 234 567 891',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Honda Civic',
        carModel: 'Honda Civic 2026',
        licensePlate: 'HC5678',
        plan: '3 Days',
        payment: '€350',
        paymentStatus: 'Pending',
        status: 'Runing',
    },
    {
        id: 'Ik-20250',
        startDate: '01 Oct 2026',
        endDate: '05 Oct 2026',
        clientName: 'Sarah Williams',
        clientEmail: 'sarah@example.com',
        clientPhone: '+1 234 567 892',
        carImage: 'https://via.placeholder.com/150',
        carName: 'BMW X5',
        carModel: 'BMW X5 2026',
        licensePlate: 'BX9012',
        plan: '4 Days',
        payment: '$800',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20251',
        startDate: '10 Nov 2026',
        endDate: '12 Nov 2026',
        clientName: 'James Brown',
        clientEmail: 'james@example.com',
        clientPhone: '+1 234 567 893',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Audi A4',
        carModel: 'Audi A4 2026',
        licensePlate: 'AD3456',
        plan: '2 Days',
        payment: '€450',
        paymentStatus: 'Pending',
        status: 'Upcoming',
    },
    {
        id: 'Ik-20252',
        startDate: '20 Dec 2026',
        endDate: '25 Dec 2026',
        clientName: 'Emily Davis',
        clientEmail: 'emily@example.com',
        clientPhone: '+1 234 567 894',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Mercedes-Benz C-Class',
        carModel: 'Mercedes-Benz C-Class 2026',
        licensePlate: 'MB7890',
        plan: '5 Days',
        payment: '$900',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20253',
        startDate: '05 Jan 2027',
        endDate: '10 Jan 2027',
        clientName: 'David Wilson',
        clientEmail: 'david@example.com',
        clientPhone: '+1 234 567 895',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Ford Mustang',
        carModel: 'Ford Mustang 2026',
        licensePlate: 'FM1234',
        plan: '5 Days',
        payment: '€600',
        paymentStatus: 'Pending',
        status: 'Runing',
    },
    {
        id: 'Ik-20254',
        startDate: '15 Feb 2027',
        endDate: '18 Feb 2027',
        clientName: 'Jessica Taylor',
        clientEmail: 'jessica@example.com',
        clientPhone: '+1 234 567 896',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Chevrolet Camaro',
        carModel: 'Chevrolet Camaro 2026',
        licensePlate: 'CC5678',
        plan: '3 Days',
        payment: '€400',
        paymentStatus: 'Pending',
        status: 'Upcoming',
    },
    {
        id: 'Ik-20255',
        startDate: '01 Mar 2027',
        endDate: '05 Mar 2027',
        clientName: 'Daniel Anderson',
        clientEmail: 'daniel@example.com',
        clientPhone: '+1 234 567 897',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Tesla Model 3',
        carModel: 'Tesla Model 3 2026',
        licensePlate: 'TM9012',
        plan: '4 Days',
        payment: '$700',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20256',
        startDate: '10 Apr 2027',
        endDate: '12 Apr 2027',
        clientName: 'Laura Martinez',
        clientEmail: 'laura@example.com',
        clientPhone: '+1 234 567 898',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Nissan Altima',
        carModel: 'Nissan Altima 2026',
        licensePlate: 'NA3456',
        plan: '2 Days',
        payment: '€300',
        paymentStatus: 'Pending',
        status: 'Runing',
    },
    {
        id: 'Ik-20257',
        startDate: '20 May 2027',
        endDate: '25 May 2027',
        clientName: 'Kevin Thomas',
        clientEmail: 'kevin@example.com',
        clientPhone: '+1 234 567 899',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Hyundai Elantra',
        carModel: 'Hyundai Elantra 2026',
        licensePlate: 'HE7890',
        plan: '5 Days',
        payment: '$550',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20258',
        startDate: '05 Jun 2027',
        endDate: '10 Jun 2027',
        clientName: 'Amanda White',
        clientEmail: 'amanda@example.com',
        clientPhone: '+1 234 567 900',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Kia Optima',
        carModel: 'Kia Optima 2026',
        licensePlate: 'KO1234',
        plan: '5 Days',
        payment: '€350',
        paymentStatus: 'Pending',
        status: 'Upcoming',
    },
    {
        id: 'Ik-20259',
        startDate: '15 Jul 2027',
        endDate: '18 Jul 2027',
        clientName: 'Robert Harris',
        clientEmail: 'robert@example.com',
        clientPhone: '+1 234 567 901',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Volkswagen Jetta',
        carModel: 'Volkswagen Jetta',
        licensePlate: 'VJ5678',
        plan: '3 Days',
        payment: '€400',
        paymentStatus: 'Paid',
        status: 'Completed',
    },
    {
        id: 'Ik-20260',
        startDate: '01 Aug 2027',
        endDate: '05 Aug 2027',
        clientName: 'Sophia Clark',
        clientEmail: 'sophia@example.com',
        clientPhone: '+1 234 567 902',
        carImage: 'https://via.placeholder.com/150',
        carName: 'Subaru Impreza',
        carModel: 'Subaru Impreza',
        licensePlate: 'SI9012',
        plan: '4 Days',
        payment: '$600',
        paymentStatus: 'Pending',
        status: 'Runing',
    },
]

// Filter options for status
export const statusFilterOptions = [
    { value: 'all', label: 'All Status' },
    { value: 'Completed', label: 'Completed' },
    { value: 'Runing', label: 'Runing' },
    { value: 'Upcoming', label: 'Upcoming' },
]
