import type { Car } from '@/types'

export const carListData: Car[] = [
  {
    id: '1',
    name: 'Audi S60',
    carNumber: 'DHA-1234',
    description: 'Or similar upper class',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    suitcases: '2 Suitcases',
    location: 'IPH Road-04 Mohakhali, Dhaka',
    fuelPolicy: 'Fair',
    kilometers: '1,400 km free',
    climate: 'Automatic',
    amount: 46.91,
    priceDuration: 'Price for 3 days',
    pricing: {
      oneDay: 46.91,
      threeDays: 128.1,
      sevenDays: 200.91,
      fourteenDays: 500,
      oneMonth: 900,
    },
    weekend: {
      selectedDays: ['Fri', 'Sat', 'Sun'],
      weekendPrice: 46.91,
    },
    carClass: 'Upper Class',
    rating: 4.5,
    owner: {
      name: 'John Smith',
      email: 'john.smith@example.com',
      phone: '+1 234 567 8900',
    },
    insuranceCoverage: '<h2>Insurance & Coverage</h2><p>Comprehensive insurance coverage is included in your rental. This includes:</p><ul><li>Third-party liability insurance</li><li>Collision damage waiver</li><li>Theft protection</li><li>Roadside assistance</li></ul>',
    termsConditions: '<h2>Terms & Conditions</h2><p>By renting this vehicle, you agree to the following terms:</p><ul><li>Valid driver\'s license required</li><li>Minimum age: 25 years</li><li>Credit card required for deposit</li><li>No smoking in the vehicle</li><li>Return vehicle in the same condition</li></ul>',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'BMW 3 Series',
    carNumber: 'DHA-5678',
    description: 'Or similar compact class',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    suitcases: '1 Suitcase',
    location: 'Gulshan-2, Dhaka',
    fuelPolicy: 'Full to Full',
    kilometers: '2,000 km free',
    climate: 'Manual',
    amount: 42.50,
    priceDuration: 'Price for 3 days',
    pricing: {
      oneDay: 42.50,
      threeDays: 115.00,
      sevenDays: 180.00,
      fourteenDays: 450.00,
      oneMonth: 800.00,
    },
    weekend: {
      selectedDays: ['Fri', 'Sat'],
      weekendPrice: 45.00,
    },
    carClass: 'Compact Class',
    rating: 4.3,
    owner: {
      name: 'Sarah Johnson',
      email: 'sarah.johnson@example.com',
      phone: '+1 234 567 8901',
    },
    insuranceCoverage: '<h2>Insurance & Coverage</h2><p>Standard insurance package includes:</p><ul><li>Basic liability coverage</li><li>Collision protection</li><li>24/7 roadside support</li></ul>',
    termsConditions: '<h2>Terms & Conditions</h2><p>Rental terms:</p><ul><li>Valid license required</li><li>Age 23+</li><li>Security deposit: $200</li><li>No pets allowed</li></ul>',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    id: '3',
    name: 'Mercedes C-Class',
    carNumber: 'DHA-9012',
    description: 'Or similar middle class',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    suitcases: '3 Suitcases',
    location: 'Banani, Dhaka',
    fuelPolicy: 'Same to Same',
    kilometers: 'Unlimited',
    climate: 'Automatic',
    amount: 48.75,
    priceDuration: 'Price for 3 days',
    carClass: 'Middle Class',
    rating: 4.7,
    owner: {
      name: 'Michael Brown',
      email: 'michael.brown@example.com',
      phone: '+1 234 567 8902',
    },
    insuranceCoverage: '<h2>Insurance & Coverage</h2><p>Premium insurance coverage:</p><ul><li>Full comprehensive insurance</li><li>Zero excess option</li><li>Personal accident insurance</li><li>Emergency breakdown service</li></ul>',
    termsConditions: '<h2>Terms & Conditions</h2><p>Premium rental terms:</p><ul><li>Driver age: 21+</li><li>International license accepted</li><li>Deposit: $300</li><li>Free cancellation up to 24h</li></ul>',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-17',
  },
  {
    id: '4',
    name: 'Toyota Corolla',
    carNumber: 'DHA-3456',
    description: 'Or similar small cars',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    doors: 4,
    transmission: 'Manual',
    seats: 5,
    suitcases: '2 Suitcases',
    location: 'Dhanmondi, Dhaka',
    fuelPolicy: 'Pre-paid',
    kilometers: '1,000 km free',
    climate: 'Manual',
    amount: 35.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Small Cars',
    rating: 4.2,
    owner: {
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      phone: '+1 234 567 8903',
    },
    insuranceCoverage: '<h2>Insurance & Coverage</h2><p>Economy insurance package:</p><ul><li>Basic third-party insurance</li><li>Collision coverage</li><li>Standard roadside assistance</li></ul>',
    termsConditions: '<h2>Terms & Conditions</h2><p>Economy rental terms:</p><ul><li>Age requirement: 25+</li><li>Local license only</li><li>Deposit: $150</li><li>Mileage limit applies</li></ul>',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    id: '5',
    name: 'Porsche 911',
    carNumber: 'DHA-7890',
    description: 'Or similar premium class',
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=400',
    doors: 2,
    transmission: 'Automatic',
    seats: 4,
    suitcases: '1 Suitcase',
    location: 'Uttara, Dhaka',
    fuelPolicy: 'Full to Empty',
    kilometers: 'Unlimited',
    climate: 'Automatic',
    amount: 125.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Premium Class',
    rating: 4.9,
    owner: {
      name: 'David Wilson',
      email: 'david.wilson@example.com',
      phone: '+1 234 567 8904',
    },
    insuranceCoverage: '<h2>Insurance & Coverage</h2><p>Luxury insurance package:</p><ul><li>Premium comprehensive coverage</li><li>Zero deductible option</li><li>Concierge service</li><li>VIP roadside assistance</li><li>Replacement vehicle guarantee</li></ul>',
    termsConditions: '<h2>Terms & Conditions</h2><p>Premium rental terms:</p><ul><li>Age: 30+</li><li>Premium license required</li><li>Deposit: $500</li><li>Unlimited mileage</li><li>Priority customer support</li></ul>',
    createdAt: '2024-01-19',
    updatedAt: '2024-01-19',
  },
  {
    id: '6',
    name: 'Volkswagen Golf',
    carNumber: 'DHA-2468',
    description: 'Or similar compact class',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    doors: 5,
    transmission: 'Manual',
    seats: 5,
    suitcases: '2 Suitcases',
    location: 'Mirpur, Dhaka',
    fuelPolicy: 'Fair',
    kilometers: '1,500 km free',
    climate: 'Manual',
    amount: 38.50,
    priceDuration: 'Price for 3 days',
    carClass: 'Compact Class',
    rating: 4.1,
    owner: {
      name: 'Lisa Anderson',
      email: 'lisa.anderson@example.com',
      phone: '+1 234 567 8905',
    },
    insuranceCoverage: '<h2>Insurance & Coverage</h2><p>Standard insurance includes:</p><ul><li>Third-party liability</li><li>Collision damage waiver</li><li>Basic roadside assistance</li><li>Theft protection</li></ul>',
    termsConditions: '<h2>Terms & Conditions</h2><p>Standard rental terms:</p><ul><li>Driver age: 24+</li><li>Valid license required</li><li>Security deposit: $180</li><li>Standard mileage included</li></ul>',
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '7',
    name: 'BMW 3 Series',
    description: 'Or similar compact class',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    amount: 42.50,
    priceDuration: 'Price for 3 days',
    carClass: 'Compact Class',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    id: '8',
    name: 'Mercedes C-Class',
    description: 'Or similar middle class',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    amount: 48.75,
    priceDuration: 'Price for 3 days',
    carClass: 'Middle Class',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-17',
  },
  {
    id: '9',
    name: 'Toyota Corolla',
    description: 'Or similar small cars',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    doors: 4,
    transmission: 'Manual',
    seats: 5,
    amount: 35.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Small Cars',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    id: '10',
    name: 'Porsche 911',
    description: 'Or similar premium class',
    image: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=400',
    doors: 2,
    transmission: 'Automatic',
    seats: 4,
    amount: 125.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Premium Class',
    createdAt: '2024-01-19',
    updatedAt: '2024-01-19',
  },
  {
    id: '11',
    name: 'Volkswagen Golf',
    description: 'Or similar compact class',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    doors: 5,
    transmission: 'Manual',
    seats: 5,
    amount: 38.50,
    priceDuration: 'Price for 3 days',
    carClass: 'Compact Class',
    createdAt: '2024-01-20',
    updatedAt: '2024-01-20',
  },
  {
    id: '12',
    name: 'Ford Focus',
    description: 'Or similar small cars',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
    doors: 5,
    transmission: 'Manual',
    seats: 5,
    amount: 32.25,
    priceDuration: 'Price for 3 days',
    carClass: 'Small Cars',
    createdAt: '2024-01-21',
    updatedAt: '2024-01-21',
  },
  {
    id: '13',
    name: 'Audi A4',
    description: 'Or similar middle class',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    amount: 45.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Middle Class',
    createdAt: '2024-01-22',
    updatedAt: '2024-01-22',
  },
  {
    id: '14',
    name: 'BMW 5 Series',
    description: 'Or similar upper class',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    amount: 55.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Upper Class',
    createdAt: '2024-01-23',
    updatedAt: '2024-01-23',
  },
  {
    id: '15',
    name: 'Mercedes S-Class',
    description: 'Or similar premium class',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400',
    doors: 4,
    transmission: 'Automatic',
    seats: 5,
    amount: 150.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Premium Class',
    createdAt: '2024-01-24',
    updatedAt: '2024-01-24',
  },
  {
    id: '16',
    name: 'Honda Civic',
    description: 'Or similar compact class',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
    doors: 4,
    transmission: 'Manual',
    seats: 5,
    amount: 36.00,
    priceDuration: 'Price for 3 days',
    carClass: 'Compact Class',
    createdAt: '2024-01-25',
    updatedAt: '2024-01-25',
  },
]

export const carClassFilterOptions = [
  { value: 'all', label: 'All Classes' },
  { value: 'Upper Class', label: 'Upper Class' },
  { value: 'Small Cars', label: 'Small Cars' },
  { value: 'Compact Class', label: 'Compact Class' },
  { value: 'Middle Class', label: 'Middle Class' },
  { value: 'Premium Class', label: 'Premium Class' },
]

